services:
    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./data/nginx/app.conf:/etc/nginx/nginx.conf
