services:
    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./data/nginx/app.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes: 
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email victormamed2016@gmail.com -d anthero.xyz --agree-tos
    
